### ISSUE TITLE
Add TTN Update Cronjob

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/iot-lora-controller#7]
Location of the gateway if in TTN mode fake GPS is got from the TTN console.

Check every X minutes for location change, update the packet forwarder and then reload the forwarder.

**Comment by shawaj** [comment]
Does the GPS data come from the GPS add on if installed?

**Comment by ryanteck** [comment]
Should do and should update automatically. This is just for those that don't. 

Currently the user has to set it in the TTN console and on the gateway. With this change fully implemented (only half at the moment) it'll update it based on what is on the TTN console.

**Comment by shawaj** [comment]
Awesome!

**Comment by ryanteck** [comment]
Changed name of this issue.

As well as the location we can make it even easier for users than before! Just a case of asking the user for the Gateway ID and the Key. And then we can get all of the details including router, location etc from 
https://account.thethingsnetwork.org/api/v2/gateways/ryanteck-ps-1

This should make it even easier than before.

**Comment by ryanteck** [comment]
A majority of these has been completed, pending testing.

**Comment by ryanteck** [comment]
This is now done to run every time the config file is changed or when the packet forwarder is restarted.
